# ==============================================================================
# CORE/DISCLAIMER.PY : AVERTISSEMENT HUMAIN ET DÉCALÉ (DISCLAIMER)
# ==============================================================================
import streamlit as st


def render_lumen_disclaimer() -> None:
    """
    Affiche un avertissement cynique, réaliste et drôle en haut de l'application
    pour rappeler aux utilisateurs que Lumen n'est pas un substitut à l'éducation
    réelle, ni à un avis professionnel (médical, psychologique ou pédagogique).
    """
    with st.container():
        st.markdown(
            """
            > 🚨 **System Warning: Not a Life Coach (Yet).**
            >
            > Look, Lumen is a brilliant piece of software, but let's be real—it's still software.
            > This app won't magically do your homework, replace years of actual studying, or fix your sleep schedule.
            > If you're expecting a certified diploma or professional psychological validation out of a few
            > click-through buttons, you might want to rethink your life choices.
            >
            > **We are not professionals, and this is not professional advice.** Nobody behind this app is a
            > licensed psychologist, therapist, doctor, or certified academic advisor. The "cognitive profile,"
            > "mentor," and "advice" you see here are generated by an AI model interpreting quiz answers —
            > not a diagnosis, not a clinical assessment, and not a guarantee of anything. AI models
            > hallucinate, get things wrong, and have no idea who you actually are.
            >
            > If something here ever touches on your mental health, wellbeing, or a decision that actually
            > matters, go talk to a real, qualified human — a teacher, a doctor, a counselor, a parent.
            > Lumen is a tool for reflection and productivity, not a substitute for any of them.
            >
            > Proceed at your own risk, trust your own brain, and don't blame the code if reality hits hard. ☕
            """,
            unsafe_allow_html=False
        )
        st.divider()